version: '3'

services:
  app:
    build: .
    command: ["chmod", "+x", ".docker/entrypoint.sh"]
    entrypoint: ./.docker/entrypoint.sh
    container_name: imersao-fullcycle-store-frontend-app
    ports:
      - 3001:3000
    volumes:
      - .:/home/node/app